version: '2'
services:
  monitoring-api:
    build: .
    command: node --inspect=0.0.0.0:9229 index.js
    ports:
    - 9229:9229
    - 6767:6767
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${PWD}:/usr/src/app